// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms
// will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do
// not exceed four million, find the sum of the even-valued terms.

var fibonacci_sum = function(max){
  var prev = 2;
  var prev_prev = 1;
  var current = prev + prev_prev;
  var sum = 2;
  console.log(prev_prev);
  console.log(prev);
  while (current <= max){
    if (current % 2 == 0){
      sum += current;
    }
    console.log(current);
    prev_prev = prev;
    prev = current;
    current = prev + prev_prev;
  };

  console.log("The total of all even numbers in the sequence is: " + sum );

};

fibonacci_sum(4000000);
